/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulariomenu;

import java.awt.Color;

/**
 *
 * @author Super
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        setLayout(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        mnuOpciones = new javax.swing.JMenu();
        mnuRojo = new javax.swing.JMenuItem();
        mnuVerde = new javax.swing.JMenuItem();
        mnuAzul = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuOpciones.setText("Opciones");

        mnuRojo.setText("Rojo");
        mnuRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRojoActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuRojo);

        mnuVerde.setText("Verde");
        mnuVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVerdeActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuVerde);

        mnuAzul.setText("Azul");
        mnuAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAzulActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuAzul);

        jMenuBar2.add(mnuOpciones);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRojoActionPerformed
        this.getContentPane().setBackground(Color.red);
    }//GEN-LAST:event_mnuRojoActionPerformed

    private void mnuVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVerdeActionPerformed
        this.getContentPane().setBackground(Color.green);
    }//GEN-LAST:event_mnuVerdeActionPerformed

    private void mnuAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAzulActionPerformed
        this.getContentPane().setBackground(Color.blue);
    }//GEN-LAST:event_mnuAzulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem mnuAzul;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JMenuItem mnuRojo;
    private javax.swing.JMenuItem mnuVerde;
    // End of variables declaration//GEN-END:variables
}
