/*
 * Copyright (C) 2014 Luis Cabrerizo Gómez
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package formularios;

import java.awt.Component;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Luis Cabrerizo Gómez
 */
public final class DialogInformes extends javax.swing.JDialog {

    private static int contadorAutores = 0;
    private static int contadorTitulos = 0;

    private static final int MAX_FILTROS_AUTORES = 4;
    private static final int MAX_FILTROS_TITULOS = 4;

    public static int getMAX_FILTROS_AUTORES() {
        return MAX_FILTROS_AUTORES;
    }

    public static int getMAX_FILTROS_TITULOS() {
        return MAX_FILTROS_TITULOS;
    }

    public static int getContadorAutores() {
        return contadorAutores;
    }

    public static void setContadorAutores(int contadorAutores) {
        DialogInformes.contadorAutores = contadorAutores;
    }

    public static int getContadorTitulos() {
        return contadorTitulos;
    }

    public static void setContadorTitulos(int contadorTitulos) {
        DialogInformes.contadorTitulos = contadorTitulos;
    }

    /**
     * Creates new form DialogInformes
     *
     * @param parent
     * @param modal
     */
    public DialogInformes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        DialogInformes.crearCajaFiltro(tbAutores);
        DialogInformes.crearCajaFiltro(tbTitulos);

    }

    public static void eliminarCajaFiltro(PanelFiltro panel) {
        if (panel.getParent().equals(tbAutores)) {
            contadorAutores--;
            tbAutores.remove(panel);

            tbAutores.updateUI();
            tbAutores.repaint();
            
            habilitarControles(tbAutores);
        } else {
            contadorTitulos--;
            tbTitulos.remove(panel);

            tbTitulos.updateUI();
            tbTitulos.repaint();
            
            habilitarControles(tbTitulos);

        }

    }

    public static void crearCajaFiltro(JPanel tab) {

        JPanel tmp;

        if (tab.equals(tbTitulos)) {
            tmp = new PanelFiltro(contadorTitulos, tbTitulos);
            contadorTitulos++;
        } else {
            tmp = new PanelFiltro(contadorAutores, tbAutores);
            contadorAutores++;
        }

        tab.add(tmp);

        tab.updateUI();

        tab.repaint();

        habilitarControles(tab);

    }

    private static void habilitarControles(JPanel tab) {
        int valorMaximo;
        int valorActual;
        int contador = 1;

        if (tab.equals(tbTitulos)) {
            valorMaximo = MAX_FILTROS_TITULOS;
            valorActual = contadorTitulos;

        } else {
            valorMaximo = MAX_FILTROS_AUTORES;
            valorActual = contadorAutores;
        }

        for (Component panel : tab.getComponents()) {

            if (contador < valorActual) {
                ((PanelFiltro) panel).habilitaNuevo(false);
            } else {
                if (((PanelFiltro) panel).getValor() == valorMaximo) {
                    ((PanelFiltro) panel).habilitaNuevo(false);
                } else {
                    ((PanelFiltro) panel).habilitaNuevo(true);
                }
            }

            if (((PanelFiltro) panel).getValor() == 0) {
                ((PanelFiltro) panel).habilitaEliminar(false);
            } else {
                ((PanelFiltro) panel).habilitaEliminar(true);
            }
            
            contador++;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tbAutores = new javax.swing.JPanel();
        tbTitulos = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(627, 324));
        setMinimumSize(new java.awt.Dimension(627, 324));
        setName("principal"); // NOI18N
        setResizable(false);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setAutoscrolls(true);

        tbAutores.setMaximumSize(new java.awt.Dimension(400, 10));
        tbAutores.setMinimumSize(new java.awt.Dimension(400, 10));
        tbAutores.setName("Autores"); // NOI18N
        tbAutores.setPreferredSize(new java.awt.Dimension(400, 10));
        jTabbedPane1.addTab("Autores", tbAutores);

        tbTitulos.setMaximumSize(new java.awt.Dimension(400, 10));
        tbTitulos.setMinimumSize(new java.awt.Dimension(400, 10));
        tbTitulos.setName("Titulos"); // NOI18N
        tbTitulos.setPreferredSize(new java.awt.Dimension(400, 10));
        jTabbedPane1.addTab("Titulos", tbTitulos);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if(tbAutores.isShowing())
        {
            for (Component component : tbAutores.getComponents()) {
                System.out.println(Arrays.toString(((PanelFiltro)component).getFiltros()));
            }
        }
        else
        {
            for (Component component : tbTitulos.getComponents()) {
                System.out.println(Arrays.toString(((PanelFiltro)component).getFiltros()));
            }        
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogInformes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogInformes dialog = new DialogInformes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JTabbedPane jTabbedPane1;
    private static javax.swing.JPanel tbAutores;
    private static javax.swing.JPanel tbTitulos;
    // End of variables declaration//GEN-END:variables

}
