/*
 * Copyright (C) 2014 Luis Cabrerizo Gómez
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package formularios;

import db.BaseDeDatos;
import db.Resultado;
import java.sql.SQLException;
import javax.swing.ListSelectionModel;
import utiles.Mensajes;

/**
 *
 * @author Luis Cabrerizo Gómez
 */
public class DialogoMultiSelect extends javax.swing.JDialog {

    private final BaseDeDatos baseDatos;
    private String[] seleccion = new String[0];

    public String[] getSeleccion() {
        return seleccion;
    }

    /**
     * Creates new form DialogoMultiSelect
     *
     * @param parent
     * @param modal
     * @param idAutores
     */
    public DialogoMultiSelect(java.awt.Frame parent, boolean modal, String[] idAutores) {
        super(parent, modal);
        initComponents();
        baseDatos = new BaseDeDatos("root", "", "127.0.0.1:3306", "libros");

        tblValores.setColumnSelectionAllowed(false);
        tblValores.setCellSelectionEnabled(false);
        tblValores.setRowSelectionAllowed(true);
        tblValores.setCellEditor(null);

        recargarGrid();

        if (idAutores != null) {
            ListSelectionModel model = tblValores.getSelectionModel();
            model.clearSelection();

            for (String idAutor : idAutores) {
                for (int i = 0; i < tblValores.getModel().getRowCount(); i++) {
                    if (tblValores.getModel().getValueAt(i, 0).toString().equals(idAutor)) {
                        model.addSelectionInterval(i, i);
                    }
                }
            }
            tblValores.setSelectionModel(model);
        }

    }

    private void recargarGrid() {
        Resultado datos = baseDatos.consultar(
                new String[]{"IdAutor", "concat(primerNombre, ' ', apellidoPaterno) As Nombre"},
                new String[]{"Autores"},
                null,
                new String[]{"Nombre ASC"});

        try {
            tblValores.setModel(BaseDeDatos.buildTableModel(datos.getResultado()));
            tblValores.removeColumn(tblValores.getColumnModel().getColumn(0));
            tblValores.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
            tblValores.setColumnSelectionAllowed(false);
            tblValores.setRowSelectionAllowed(true);

        } catch (SQLException ex) {
            Mensajes.mostrarMensaje(ex.getMessage(), Mensajes.TipoMensaje.ERROR);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblValores = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnOk.setText("Seleccionar");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        tblValores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblValores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        seleccion = new String[tblValores.getSelectedRowCount()];
        int i = 0;

        for (int fila : tblValores.getSelectedRows()) {
            seleccion[i] = String.valueOf(tblValores.getModel().getValueAt(fila, 0));
            i++;
        }

        this.setVisible(false);
    }//GEN-LAST:event_btnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblValores;
    // End of variables declaration//GEN-END:variables
}
