/*
 * Copyright (C) 2014 Luis Cabrerizo Gómez
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package formularios;

import db.BaseDeDatos;
import db.Libro;
import db.Resultado;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import utiles.Mensajes;

/**
 *
 * @author Luis Cabrerizo Gómez
 */
public class FormularioCaratula extends javax.swing.JPanel {

    private String isbn;
    private BaseDeDatos baseDatos;
    private Libro libro;

    public FormularioCaratula(String isbn) {
        initComponents();

        this.isbn = isbn;
        setVisible(true);

        libro = new Libro();
        libro.setIsbn(this.isbn);

        baseDatos = new BaseDeDatos("root", "", "127.0.0.1:3306", "libros");

        try {
            Resultado datos = baseDatos.consultar(
                    new String[]{"*"},
                    new String[]{"titulos"},
                    new String[]{"isbn= " + this.isbn}, null);

            if (datos.isOperacionCorrecta() && datos.getResultado().next()) {
                lblTitulo.setText(datos.getResultado().getString("titulo"));

                libro.setTitulo(lblTitulo.getText());
                libro.setCopyright(datos.getResultado().getString("copyright"));
                libro.setEditorial(datos.getResultado().getString("editorial"));
                libro.setNumEdicion(datos.getResultado().getInt("numeroEdicion"));

                datos = baseDatos.consultar(
                        new String[]{"idAutor"},
                        new String[]{"isbnautor"},
                        new String[]{"isbn = " + this.isbn}, null);

                String idAutor = "";

                if (datos.isOperacionCorrecta()) {
                    while (datos.getResultado().next()) {
                        idAutor += datos.getResultado().getString("idAutor") + ",";
                    }

                    idAutor = idAutor.substring(0, idAutor.length() - 1);

                    libro.setAutores(idAutor.split(","));

                    lblAutores.setText(baseDatos.consultaNombreAutor(idAutor.split(",")));

                }

                if (!datos.getResultado().isClosed()) {
                    datos.getResultado().close();
                }

            }
        } catch (SQLException ex) {
            Mensajes.mostrarMensaje(ex.getMessage(), Mensajes.TipoMensaje.ERROR);
        }

    }

    /**
     * Creates new form FormularioCaratula
     */
    public FormularioCaratula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCaratula = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblAutores = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(126, 200));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCaratula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCaratula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/no_book.png"))); // NOI18N
        lblCaratula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCaratulaMouseClicked(evt);
            }
        });
        add(lblCaratula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Titulo");
        lblTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblTitulo.setFocusable(false);
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitulo.setMaximumSize(new java.awt.Dimension(125, 15));
        lblTitulo.setMinimumSize(new java.awt.Dimension(125, 15));
        lblTitulo.setPreferredSize(new java.awt.Dimension(125, 15));
        lblTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloMouseClicked(evt);
            }
        });
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, 20));

        lblAutores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAutores.setText("Autores");
        lblAutores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAutores.setMaximumSize(new java.awt.Dimension(125, 15));
        lblAutores.setMinimumSize(new java.awt.Dimension(125, 15));
        lblAutores.setPreferredSize(new java.awt.Dimension(125, 15));
        lblAutores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAutoresMouseClicked(evt);
            }
        });
        add(lblAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 120, 20));

        lblISBN.setEnabled(false);
        add(lblISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void lblTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloMouseClicked
        pulsado();
    }//GEN-LAST:event_lblTituloMouseClicked

    private void lblAutoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAutoresMouseClicked
        pulsado();
    }//GEN-LAST:event_lblAutoresMouseClicked

    private void lblCaratulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCaratulaMouseClicked
        pulsado();
    }//GEN-LAST:event_lblCaratulaMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        pulsado();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAutores;
    private javax.swing.JLabel lblCaratula;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

    private void pulsado() {
        FormularioLibros form = new FormularioLibros(libro);
        form.setVisible(true);
        form.pack();

        FormularioPrincipal frame = (FormularioPrincipal) this.getTopLevelAncestor();

        form.setVisible(true);
        form.pack();

        frame.jDesktopPane1.removeAll();
        frame.jDesktopPane1.add(form);

        try {
            form.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Mensajes.mostrarMensaje(ex.getMessage(), Mensajes.TipoMensaje.ERROR);
        }
    }

}
