/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import db.BaseDeDatos;
import db.Resultado;
import java.awt.GridLayout;
import java.sql.SQLException;
import utiles.Mensajes;

/**
 *
 * @author Super
 */
public class FormularioBiblioteca extends javax.swing.JInternalFrame {

    private final BaseDeDatos baseDatos;
    private int paginacion = 1;
    private int paginacionMaxima = 1;

    /**
     * Creates new form FormularioBiblioteca
     */
    public FormularioBiblioteca() {
        initComponents();
        cmbTipoFiltro.setSelectedIndex(1);

        baseDatos = new BaseDeDatos("root", "", "127.0.0.1:3306", "libros");

        try {
            Resultado datos = baseDatos.consultar(
                    new String[]{"Count(*) as Total"},
                    new String[]{"titulos"}, null, null);

            if (datos.isOperacionCorrecta() && datos.getResultado().next()) {
                paginacionMaxima = (int) Math.ceil(datos.getResultado().getInt("Total") / 9f);
            }

            if (!datos.getResultado().isClosed()) {
                datos.getResultado().close();
            }

        } catch (SQLException ex) {
            Mensajes.mostrarMensaje(ex.getMessage(), Mensajes.TipoMensaje.ERROR);
        }

        refrescarLibros(paginacion);

    }

    private String[] crearFiltro() {
        String sql = "";

        switch (cmbTipoFiltro.getSelectedIndex()) {
            case 0:
                sql = "ISBN LIKE '" + txtFiltro.getText() + "%'";
                break;

            case 1:
                sql = "TITULO LIKE '" + txtFiltro.getText() + "%'";
                break;

            case 2: {
                sql = "NUMEROEDICION LIKE '" + txtFiltro.getText() + "%'";
                break;
            }
            case 3: {
                sql = "EDITORIAL LIKE '" + txtFiltro.getText() + "%'";
                break;
            }
            case 4: {
                sql = "COPYRIGHT LIKE '" + txtFiltro.getText() + "%'";
                break;
            }

        }

        return new String[]{sql};

    }

    private void refrescarLibros(int pagina) {
        try {

            Resultado datos = baseDatos.consultar(
                    new String[]{"*"},
                    new String[]{"titulos"},
                    crearFiltro(),
                    null,
                    new int[]{(pagina - 1) * 9, 9});

            if (datos.isOperacionCorrecta()) {

                pnlMain.removeAll();

                while (datos.getResultado().next()) {
                    pnlMain.setLayout(new GridLayout(0, 3, 1, 0));
                    pnlMain.add(new FormularioCaratula(datos.getResultado().getString("isbn")));
                }

                if (pagina == 1) {
                    btnLeft.setVisible(false);
                } else {
                    btnLeft.setVisible(true);
                }

                if (pagina == paginacionMaxima) {
                    btnRight.setVisible(false);
                } else {
                    btnRight.setVisible(true);
                }

                pnlMain.updateUI();

                if (!datos.getResultado().isClosed()) {
                    datos.getResultado().close();
                }

            }
        } catch (SQLException ex) {
            Mensajes.mostrarMensaje(ex.getMessage(), Mensajes.TipoMensaje.ERROR);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        btnRight = new javax.swing.JButton();
        btnLeft = new javax.swing.JButton();
        panelFiltro = new javax.swing.JPanel();
        cmbTipoFiltro = new javax.swing.JComboBox();
        txtFiltro = new javax.swing.JTextField();
        lblTipoFiltro = new javax.swing.JLabel();
        lblValorFiltro = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMain.setMaximumSize(new java.awt.Dimension(398, 457));
        pnlMain.setMinimumSize(new java.awt.Dimension(398, 457));

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        getContentPane().add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 420, 590));

        btnRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next.png"))); // NOI18N
        btnRight.setBorder(null);
        btnRight.setBorderPainted(false);
        btnRight.setContentAreaFilled(false);
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });
        getContentPane().add(btnRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 700, -1, 24));

        btnLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/prev.png"))); // NOI18N
        btnLeft.setBorder(null);
        btnLeft.setBorderPainted(false);
        btnLeft.setContentAreaFilled(false);
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });
        getContentPane().add(btnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, -1, 24));

        panelFiltro.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro"));

        cmbTipoFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ISBN", "Título", "Edición", "Editorial", "Año" }));

        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        lblTipoFiltro.setText("Tipo");

        lblValorFiltro.setText("Valor");

        javax.swing.GroupLayout panelFiltroLayout = new javax.swing.GroupLayout(panelFiltro);
        panelFiltro.setLayout(panelFiltroLayout);
        panelFiltroLayout.setHorizontalGroup(
            panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTipoFiltro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTipoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblValorFiltro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelFiltroLayout.setVerticalGroup(
            panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFiltroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoFiltro)
                    .addComponent(lblValorFiltro))
                .addContainerGap())
        );

        getContentPane().add(panelFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 420, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        paginacion++;
        refrescarLibros(paginacion);
    }//GEN-LAST:event_btnRightActionPerformed

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        paginacion--;
        refrescarLibros(paginacion);
    }//GEN-LAST:event_btnLeftActionPerformed

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        paginacion = 1;
        refrescarLibros(paginacion);

    }//GEN-LAST:event_txtFiltroKeyReleased

    /**
     * Create the GUI and show it. For thread safety, this method should be
     * invoked from the event dispatch thread.
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnRight;
    private javax.swing.JComboBox cmbTipoFiltro;
    private javax.swing.JLabel lblTipoFiltro;
    private javax.swing.JLabel lblValorFiltro;
    private javax.swing.JPanel panelFiltro;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
